In [2]:
import numpy as np

The columns in the txt file are nicely lined up. I will use this to identify each element to tokenise them.

The name identifier won't be useful, and it contains many spaces, I will skip it.

(first element often a blank space for 0 before decima) = FE

List of columns and start index:

- NUM :            3
- PGC/LEDA :       6
- Name :           19
- R.A. 1950 DEC. : 45
- Type :           61
- logD25 :         73 FE
- logR25 :         81
- BT :             86
- Vhelio :         93 FE


In [3]:
f = open("coma_gal.txt", "r")
lines = f.readlines()

index_bounds = (9, 312) # inclusive - exclusive

n_lines = lines[index_bounds[0]:index_bounds[1]]

#for i in range(len(n_lines)):
#    print(i, n_lines[i])

index = 4

for i in range(len(n_lines[index])):
    if i == 0 : continue

    if n_lines[index][i-1] == " " and n_lines[index][i] != " " :
        print(f"New item: \nindex: {i}, value: {n_lines[index][i]}\n")

New item: 
index: 3, value: 5

New item: 
index: 6, value: L

New item: 
index: 19, value: D

New item: 
index: 27, value: 2

New item: 
index: 32, value: 2

New item: 
index: 45, value: 1

New item: 
index: 61, value: E

New item: 
index: 74, value: .

New item: 
index: 81, value: .

New item: 
index: 86, value: 1

New item: 
index: 94, value: 7



In [13]:
indices = {"NUM": 0, "logD25": 1, "logR25": 2, "BT": 3, "Vhelio": 4}
col_indices = [3, 73, 81, 86, 93]#[3, 6, 45, 61, 73, 81, 86, 93]
# don't need the name, nor the angular position, nor type
def parse_lines(lines):
    #data = np.zeros((len(lines), len(col_indices)))
    data = [[0 for j in col_indices] for i in lines ]
    for i in range(len(lines)):
        l = lines[i]
        for j in range(len(col_indices)):
            c = col_indices[j]
            for k in range(c, len(l)):
                if k > c and (l[k]==" " or k==len(l)-1) :
                    print(f"{c}yeet", l[c:k])
                    #data[i][j] = float(l[c:k])
                    try :
                        #if l[c:k] == " ":
                        #    raise Exception
                        data[i][j] = float(l[c:k])
                    except:
                        cce = 0
                        data[i][j] = None
                    break
    return data
data = parse_lines(n_lines)
print(data)
#print(np.zeros((5, 2)))


3yeet 1
73yeet  
81yeet  
86yeet 18.75
93yeet  8159
3yeet 2
73yeet  .74
81yeet .13
86yeet 16.75
3yeet 3
73yeet  
81yeet  
86yeet 17.76
93yeet  6061
3yeet 4
73yeet  .62
81yeet .26
86yeet 15.36
93yeet  7460
3yeet 5
73yeet  .88
81yeet .08
86yeet 15.86
93yeet  7738
3yeet 6
73yeet  
81yeet  
86yeet 18.31
93yeet  5882
3yeet 7
73yeet  
81yeet  
86yeet 19.70
93yeet 49174
3yeet 8
73yeet  
81yeet  
86yeet 17.44
93yeet  8539
3yeet 9
73yeet  .63
81yeet .07
86yeet 16.65
93yeet  5968
3yeet 0
73yeet  .68
81yeet .10
86yeet 16.29
93yeet  5891
3yeet 1
73yeet  .92
81yeet .54
86yeet 16.20
93yeet  5097
3yeet 2
73yeet  .50
81yeet .00
86yeet 16.41
93yeet  5050
3yeet 3
73yeet  
81yeet  
86yeet 17.29
93yeet  5779
3yeet 4
73yeet  .50
81yeet .08
86yeet 17.14
93yeet  5589
3yeet 5
73yeet  .91
81yeet .04
86yeet 14.40
93yeet  7608
3yeet 6
73yeet  .84
81yeet .18
86yeet 16.16
3yeet 7
73yeet  
81yeet  
86yeet 19.11
93yeet 47535
3yeet 8
73yeet  
81yeet  
86yeet 19.43
93yeet  6635
3yeet 9
73yeet  .77
81yeet .45
86yeet 16

In [12]:
print(np.shape(data))
for i in range(np.shape(data)[0]):
    for j in range(np.shape(data)[1]):
        print(data[i][j])
    print()

(303, 5)
1.0
None
None
18.75
8159.0

2.0
0.74
0.13
16.75
0

3.0
None
None
17.76
6061.0

4.0
0.62
0.26
15.36
7460.0

5.0
0.88
0.08
15.86
7738.0

6.0
None
None
18.31
5882.0

7.0
None
None
19.7
49174.0

8.0
None
None
17.44
8539.0

9.0
0.63
0.07
16.65
5968.0

0.0
0.68
0.1
16.29
5891.0

1.0
0.92
0.54
16.2
5097.0

2.0
0.5
0.0
16.41
5050.0

3.0
None
None
17.29
5779.0

4.0
0.5
0.08
17.14
5589.0

5.0
0.91
0.04
14.4
7608.0

6.0
0.84
0.18
16.16
0

7.0
None
None
19.11
47535.0

8.0
None
None
19.43
6635.0

9.0
0.77
0.45
16.58
8223.0

0.0
0.77
0.42
16.72
7513.0

1.0
None
None
18.39
33849.0

2.0
0.7
0.11
16.12
5577.0

3.0
None
None
17.5
7579.0

4.0
1.05
0.04
14.0
7879.0

5.0
None
None
18.05
5876.0

6.0
None
None
18.31
17437.0

7.0
0.74
0.19
15.76
7486.0

8.0
None
None
19.47
8043.0

9.0
0.74
0.06
15.16
5547.0

0.0
0.78
0.14
15.56
7144.0

1.0
0.64
0.12
16.56
5233.0

2.0
0.78
0.32
16.52
7102.0

3.0
0.71
0.05
16.68
0

4.0
None
None
17.69
7085.0

5.0
0.55
0.11
16.97
6900.0

6.0
None
None
19.61
56567.0

7.0

In [10]:
print(data[0][indices["Vhelio"]])
print(np.transpose(data))

8159.0
[[1.0 2.0 3.0 ... 1.0 2.0 3.0]
 [None 0.74 None ... 0.52 0.53 None]
 [None 0.13 None ... 0.22 0.17 None]
 [18.75 16.75 17.76 ... 17.17 16.76 16.99]
 [8159.0 0 6061.0 ... 6342.0 0 0]]
